-- SJ-Facturación: esquema de base y políticas RLS de prueba para Supabase
-- Ejecutar en el editor SQL de tu proyecto Supabase.

-- Esquema de tablas
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  taxId text,
  email text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  owner uuid not null default auth.uid(),
  constraint products_owner_sku_unique unique (owner, sku)
);

create table if not exists public.priceLists (
  id bigint generated by default as identity primary key,
  name text not null,
  currency text not null
);

create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  listId bigint not null references public.priceLists(id) on delete cascade,
  productId bigint not null references public.products(id) on delete cascade,
  price numeric(12,2) not null default 0,
  constraint prices_unique_per_list_product unique (listId, productId)
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  number bigint not null,
  customerId bigint not null references public.customers(id) on delete restrict,
  date timestamptz not null,
  total numeric(12,2) not null default 0,
  constraint invoices_number_unique unique (number)
);

create table if not exists public.invoiceItems (
  id bigint generated by default as identity primary key,
  invoiceId bigint not null references public.invoices(id) on delete cascade,
  productId bigint not null references public.products(id) on delete restrict,
  qty numeric(12,3) not null default 1,
  unitPrice numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0
);

create table if not exists public.ledger (
  id bigint generated by default as identity primary key,
  customerId bigint not null references public.customers(id) on delete restrict,
  date timestamptz not null,
  type text not null check (type in ('debe','haber')),
  amount numeric(12,2) not null default 0,
  reference text
);

-- Índices para consultas frecuentes
create index if not exists idx_ledger_customer_date on public.ledger(customerId, date desc);
create index if not exists idx_prices_list_product on public.prices(listId, productId);
create index if not exists idx_invoiceitems_invoice on public.invoiceItems(invoiceId);
create index if not exists idx_invoices_customer_date on public.invoices(customerId, date desc);

-- RLS: activar y crear políticas abiertas para pruebas (no producción)
alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.priceLists enable row level security;
alter table public.prices enable row level security;
alter table public.invoices enable row level security;
alter table public.invoiceItems enable row level security;
alter table public.ledger enable row level security;

-- Conceder privilegios básicos al rol anon (para pruebas)
grant usage on schema public to anon;
grant select, insert, update, delete on all tables in schema public to anon;
alter default privileges in schema public grant select, insert, update, delete on tables to anon;

-- Políticas por tabla (select/insert/update permitidos para anon)
drop policy if exists anon_select_customers on public.customers;
drop policy if exists anon_insert_customers on public.customers;
drop policy if exists anon_update_customers on public.customers;
create policy anon_select_customers on public.customers for select to anon using (true);
create policy anon_insert_customers on public.customers for insert to anon with check (true);
create policy anon_update_customers on public.customers for update to anon using (true) with check (true);

drop policy if exists anon_select_products on public.products;
drop policy if exists anon_insert_products on public.products;
drop policy if exists anon_update_products on public.products;
create policy anon_select_products on public.products for select to anon using (true);
create policy anon_insert_products on public.products for insert to anon with check (true);
create policy anon_update_products on public.products for update to anon using (true) with check (true);

drop policy if exists anon_select_priceLists on public.priceLists;
drop policy if exists anon_insert_priceLists on public.priceLists;
drop policy if exists anon_update_priceLists on public.priceLists;
create policy anon_select_priceLists on public.priceLists for select to anon using (true);
create policy anon_insert_priceLists on public.priceLists for insert to anon with check (true);
create policy anon_update_priceLists on public.priceLists for update to anon using (true) with check (true);

drop policy if exists anon_select_prices on public.prices;
drop policy if exists anon_insert_prices on public.prices;
drop policy if exists anon_update_prices on public.prices;
create policy anon_select_prices on public.prices for select to anon using (true);
create policy anon_insert_prices on public.prices for insert to anon with check (true);
create policy anon_update_prices on public.prices for update to anon using (true) with check (true);

drop policy if exists anon_select_invoices on public.invoices;
drop policy if exists anon_insert_invoices on public.invoices;
drop policy if exists anon_update_invoices on public.invoices;
create policy anon_select_invoices on public.invoices for select to anon using (true);
create policy anon_insert_invoices on public.invoices for insert to anon with check (true);
create policy anon_update_invoices on public.invoices for update to anon using (true) with check (true);

drop policy if exists anon_select_invoiceItems on public.invoiceItems;
drop policy if exists anon_insert_invoiceItems on public.invoiceItems;
drop policy if exists anon_update_invoiceItems on public.invoiceItems;
create policy anon_select_invoiceItems on public.invoiceItems for select to anon using (true);
create policy anon_insert_invoiceItems on public.invoiceItems for insert to anon with check (true);
create policy anon_update_invoiceItems on public.invoiceItems for update to anon using (true) with check (true);

drop policy if exists anon_select_ledger on public.ledger;
drop policy if exists anon_insert_ledger on public.ledger;
drop policy if exists anon_update_ledger on public.ledger;
create policy anon_select_ledger on public.ledger for select to anon using (true);
create policy anon_insert_ledger on public.ledger for insert to anon with check (true);
create policy anon_update_ledger on public.ledger for update to anon using (true) with check (true);

-- Nota: en producción, reemplazar estas políticas por RLS basadas en autenticación
-- (p.ej. usuario/tenant) y restringir operaciones según auth.uid().